version: "3.7"

services:

  ionic-dev:
    image: tgmti/portinari-ionic:0.0.2
    build: .
    ports: 
      - 8100:8100
      - 8200:8200
      - 4200:4200
    volumes: 
      - ./app:/app
      - node_modules:/app/node_modules
    tty: true
    environment: 
      - INIT_IONIC_SERVER=false
      - INIT_IONIC_LAB=false
 
volumes: 
  node_modules: