version: "3.7"

services:

  portinari:
    image: tgmti/portinari:0.0.1-buster
    build: .
    ports:
      - 4200:4200
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    tty: true
    environment:
      - INIT_IONIC_SERVER=false

volumes:
  node_modules: